# Example of using an existing secret for CNPG authentication
# This prevents password regeneration on helm upgrades

# First, create the secret with your desired credentials:
---
apiVersion: v1
kind: Secret
metadata:
  name: pelican-db-credentials
type: kubernetes.io/basic-auth
stringData:
  username: pelican
  password: "your-secure-password-here"

---
# Then in your values.yaml or helm install command:
# helm install pelican-panel ./charts/pelican-panel \
#   --set cnpg.enabled=true \
#   --set cnpg.auth.existingSecret=pelican-db-credentials

# Or in values.yaml:
# cnpg:
#   enabled: true
#   auth:
#     existingSecret: pelican-db-credentials
#     existingSecretUsernameKey: username  # optional, defaults to "username"
#     existingSecretPasswordKey: password  # optional, defaults to "password"
