image:
  repository: ghcr.io/pelican-dev/panel
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

# Enable CloudNativePG for database
cnpg:
  enabled: true
  instances: 1
  cluster:
    storage:
      storageClass: "longhorn"

persistence:
  enabled: true
  storageClass: "longhorn"
  data:
    size: 10Gi
  logs:
    size: 5Gi

pelican:
  appUrl: "https://pelican.jacob.brookins.house"
  appEnvironment: "production"
  appDebug: false
  adminEmail: "jacob@brookins.email"
  adminUsername: "jacob"

ingress:
  enabled: true
  className: traefik
  hosts:
    - host: pelican.jacob.brookins.house
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - pelican.jacob.brookins.house
