apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pelican-panel.fullname" . }}-secret
  labels:
    {{- include "pelican-panel.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Application Key
  {{- if .Values.pelican.appKey }}
  APP_KEY: {{ .Values.pelican.appKey | quote }}
  {{- else }}
  APP_KEY: {{ printf "base64:%s" (randAlphaNum 32 | b64enc) | quote }}
  {{- end }}
  
  # Admin Credentials
  ADMIN_EMAIL: {{ .Values.pelican.adminEmail | quote }}
  ADMIN_USERNAME: {{ .Values.pelican.adminUsername | quote }}
  {{- if .Values.pelican.adminPassword }}
  ADMIN_PASSWORD: {{ .Values.pelican.adminPassword | quote }}
  {{- else }}
  ADMIN_PASSWORD: {{ randAlphaNum 16 | quote }}
  {{- end }}
  
  # Database Password (only for external database without existing secret)
  {{- if and .Values.externalDatabase.enabled (not .Values.externalDatabase.existingSecret) }}
  database-password: {{ .Values.externalDatabase.password | quote }}
  {{- end }}
  
  # Redis Password (only if redis enabled without existing secret)
  {{- if and .Values.redis.enabled .Values.redis.password (not .Values.redis.existingSecret) }}
  redis-password: {{ .Values.redis.password | quote }}
  {{- end }}
  
  # Mail Password
  {{- if .Values.pelican.mailPassword }}
  MAIL_PASSWORD: {{ .Values.pelican.mailPassword | quote }}
  {{- end }}