apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pelican-panel.fullname" . }}-secret
  labels:
    {{- include "pelican-panel.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Application Key
  {{- if .Values.pelican.appKey }}
  APP_KEY: {{ .Values.pelican.appKey | quote }}
  {{- else }}
  APP_KEY: {{ printf "base64:%s" (randAlphaNum 32 | b64enc) | quote }}
  {{- end }}

  # Admin Credentials
  ADMIN_EMAIL: {{ .Values.pelican.adminEmail | quote }}

  # Mail Password
  {{- if .Values.pelican.mailPassword }}
  MAIL_PASSWORD: {{ .Values.pelican.mailPassword | quote }}
  {{- end }}
