{{- if .Values.cnpg.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pelican-panel.fullname" . }}-cnpg-app
  labels:
    {{- include "pelican-panel.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: pelican
  password: {{ randAlphaNum 32 | quote }}
{{- end }}