{{- if and .Values.cnpg.enabled (not .Values.cnpg.auth.existingSecret) }}
{{- $secretName := printf "%s-cnpg-app" (include "pelican-panel.fullname" .) }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "pelican-panel.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: pelican
  password: {{ if $existingSecret }}{{ index $existingSecret.data "password" | b64dec | quote }}{{ else }}{{ randAlphaNum 32 | quote }}{{ end }}
{{- end }}
