name: Pre-commit

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@7edac99f961f18b581bbd960d59d049f04c0002f # v6
        with:
          enable-cache: true

      - name: Install Python
        run: uv python install 3.12

      - name: Install dependencies
        run: uv sync --dev

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Install helm-docs
        run: |
          cd /tmp
          wget https://github.com/norwoodj/helm-docs/releases/download/v1.13.1/helm-docs_1.13.1_Linux_x86_64.tar.gz
          tar -xvf helm-docs_1.13.1_Linux_x86_64.tar.gz
          sudo mv helm-docs /usr/local/bin

      - name: Run pre-commit
        run: uv run pre-commit run --all-files
